#!/usr/bin/env python3
"""
P4 — Activity-proximity validation of generated molecules (post-hoc oracle).

For every molecule generated by the canonical P4 benchmark (v9: 20 seeds x
4 methods, `results/benchmark_molecules/p4_benchmark_merged.csv` and
`results/pareto/p4_multiobj_benchmark.csv`), compute the maximum Morgan-2
Tanimoto similarity to known antimalarial actives from the independent public
ChEMBL malaria IC50/EC50 dataset (19,321 actives / 3,126 inactives,
`Project5_GNN_Transformer_DrugDiscovery/results/p5_public_chembl_malaria.csv`).

This is a POST-HOC validation oracle: it does NOT change the MCTS reward, so
the canonical v9 benchmark numbers stay valid. It answers the question:
"do the molecules P4 generates resemble experimentally active antimalarials?"

Comparisons:
  - per-method mean/median max-Tanimoto-to-actives (MCTS, GA, Random, Greedy)
  - active-vs-inactive enrichment: max-Tanimoto-to-actives vs
    max-Tanimoto-to-inactives per molecule (higher ratio = closer to actives)
  - baseline: randomly grown fragment chains (same fragment vocabulary and
    length distribution) — Mann-Whitney U vs each method

Outputs:
    results/p4_activity_validation_report.json
    results/p4_activity_validation_summary.txt

Usage:
    python scripts/p4_activity_oracle_validation.py
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
from scipy import stats

P4 = Path(__file__).resolve().parents[1]
SCRIPTS = Path(__file__).parent

PUBLIC_CSV = (
    P4.parent
    / "Project5_GNN_Transformer_DrugDiscovery"
    / "results"
    / "p5_public_chembl_malaria.csv"
)
GENERATED_CSV = P4 / "results/pareto/p4_multiobj_benchmark.csv"
GEN_MOLECULES_CSV = P4 / "results/benchmark_molecules/p4_benchmark_merged.csv"

N_BASELINE = 400
SEED = 42


def load_public(csv_path: Path):
    """Return (active_smiles, inactive_smiles)."""
    df = pd.read_csv(csv_path)
    df = df.dropna(subset=["smiles", "activity"]).drop_duplicates("smiles")
    act = df.loc[df["activity"] >= 0.5, "smiles"].astype(str).tolist()
    ina = df.loc[df["activity"] < 0.5, "smiles"].astype(str).tolist()
    return act, ina


def load_generated():
    """Load P4 v9 generated molecules (method, smiles)."""
    rows = []
    for csv_path in (GENERATED_CSV, GEN_MOLECULES_CSV):
        if not csv_path.exists():
            continue
        df = pd.read_csv(csv_path)
        for _, r in df.iterrows():
            smi = str(r.get("smiles", r.get("best_smiles", "")))
            if smi and smi != "nan":
                rows.append((str(r["method"]), smi))
    # dedupe (method, smiles)
    seen, out = set(), []
    for m, s in rows:
        k = (m, s)
        if k not in seen:
            seen.add(k)
            out.append((m, s))
    return out


def random_fragment_baseline(rng: np.random.Generator, n: int = N_BASELINE,
                             max_steps: int = 10) -> list[str]:
    """Grow random fragment chains (same vocabulary as the P4 env)."""
    vocab = ["c1ccccc1", "CC", "C=O", "CN", "CF", "CCO", "CCC", "CCCC",
             "c1ccncc1", "C1CCCC1", "CC(C)(C)", "c1cncnc1", "c1ccsc1",
             "c1ccoc1", "c1cnccn1", "NC(N)=O", "C(=O)O", "OC", "N", "C1CCOC1"]
    out = []
    for _ in range(n):
        nf = int(rng.integers(1, max_steps + 1))
        parts = [rng.choice(vocab) for _ in range(nf)]
        smi = ".".join(parts)
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        out.append(Chem.MolToSmiles(mol))
    return out


def dense_fp_matrix(smiles_list: list[str], gen) -> tuple[np.ndarray, list[str]]:
    """Dense 2048-bit fingerprint matrix for a SMILES list (valid entries only)."""
    rows, valid = [], []
    for smi in smiles_list:
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            rows.append(np.zeros(2048, dtype=np.float32))
            continue
        arr = np.zeros(2048, dtype=np.float32)
        onbits = list(gen.GetFingerprint(mol).GetOnBits())
        if onbits:
            arr[onbits] = 1.0
        rows.append(arr)
        valid.append(smi)
    return np.array(rows), valid


def max_tanimoto(query_onbits: list[int], query_norm: float,
                 lib: np.ndarray, norms: np.ndarray) -> float:
    if not query_onbits:
        return 0.0
    q = np.zeros(2048, dtype=np.float32)
    q[query_onbits] = 1.0
    inter = lib @ q
    denom = query_norm + norms - inter
    denom = np.maximum(denom, 1e-8)
    return float(np.max(inter / denom))


def main() -> int:
    t0 = time.perf_counter()
    print("P4 — Activity-proximity validation of generated molecules")
    print("=" * 64)

    if not PUBLIC_CSV.exists():
        print(f"ERROR: public dataset not found: {PUBLIC_CSV}")
        return 1
    act_smiles, ina_smiles = load_public(PUBLIC_CSV)
    print(f"Public ChEMBL: {len(act_smiles)} actives / {len(ina_smiles)} inactives")

    gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
    print("Building active/inactive library matrices...", flush=True)
    act_mat, act_valid = dense_fp_matrix(act_smiles, gen)
    ina_mat, ina_valid = dense_fp_matrix(ina_smiles, gen)
    act_norms = act_mat.sum(axis=1)
    ina_norms = ina_mat.sum(axis=1)
    print(f"  valid actives {len(act_valid)} / valid inactives {len(ina_valid)}")

    generated = load_generated()
    print(f"Generated molecules loaded: {len(generated)}")
    if not generated:
        print("ERROR: no generated molecules found")
        return 1

    # Per-molecule scores
    records = []
    for method, smi in generated:
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        fp = gen.GetFingerprint(mol)
        onbits = list(fp.GetOnBits())
        qn = float(len(onbits))
        ta = max_tanimoto(onbits, qn, act_mat, act_norms)
        ti = max_tanimoto(onbits, qn, ina_mat, ina_norms)
        records.append({"method": method, "smiles": smi,
                        "max_tan_actives": ta, "max_tan_inactives": ti,
                        "actives_over_inactives": ta / max(ti, 1e-6)})
    gen_df = pd.DataFrame(records)

    # Baseline
    rng = np.random.default_rng(SEED)
    baseline = random_fragment_baseline(rng)
    base_rows = []
    for smi in baseline:
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        fp = gen.GetFingerprint(mol)
        onbits = list(fp.GetOnBits())
        qn = float(len(onbits))
        ta = max_tanimoto(onbits, qn, act_mat, act_norms)
        ti = max_tanimoto(onbits, qn, ina_mat, ina_norms)
        base_rows.append({"method": "baseline_random_fragments", "smiles": smi,
                          "max_tan_actives": ta, "max_tan_inactives": ti,
                          "actives_over_inactives": ta / max(ti, 1e-6)})
    base_df = pd.DataFrame(base_rows)

    report = {
        "public_dataset": str(PUBLIC_CSV),
        "n_public_actives": len(act_smiles),
        "n_public_inactives": len(ina_smiles),
        "n_baseline_fragments": len(base_df),
        "methods": {},
    }
    lines = [
        "P4 activity-proximity validation (post-hoc, reward unchanged)",
        f"Public ChEMBL malaria IC50/EC50: {len(act_smiles)} actives / {len(ina_smiles)} inactives",
        "",
        f"{'method':<26s}{'n':>5s}{'meanT_act':>11s}{'medT_act':>11s}{'T_act/ina':>12s}{'vs_base_p':>12s}",
    ]

    for method in sorted(gen_df["method"].unique()) + ["baseline_random_fragments"]:
        if method == "baseline_random_fragments":
            sub = base_df
        else:
            sub = gen_df[gen_df["method"] == method]
        ta = sub["max_tan_actives"].values
        ratio = sub["actives_over_inactives"].values
        p_vs_base = float("nan")
        if method != "baseline_random_fragments":
            u, p = stats.mannwhitneyu(ta, base_df["max_tan_actives"].values,
                                      alternative="greater")
            p_vs_base = float(p)
        lines.append(
            f"{method:<26s}{len(sub):>5d}{np.mean(ta):>11.4f}{np.median(ta):>11.4f}"
            f"{np.mean(ratio):>12.3f}{p_vs_base:>12.5f}"
        )
        report["methods"][method] = {
            "n": int(len(sub)),
            "mean_max_tan_actives": float(np.mean(ta)),
            "median_max_tan_actives": float(np.median(ta)),
            "mean_actives_over_inactives": float(np.mean(ratio)),
            "mannwhitney_greater_vs_baseline_p": p_vs_base,
        }

    # Active-vs-inactive discrimination per method (higher = closer to actives)
    lines.append("")
    lines.append("Active/inactive proximity ratio (mean; >1 = closer to known actives):")
    for method in sorted(gen_df["method"].unique()):
        sub = gen_df[gen_df["method"] == method]
        lines.append(f"  {method:<24s} {np.mean(sub['actives_over_inactives']):.3f}")

    summary = "\n".join(lines)
    print("\n" + summary)
    (P4 / "results/p4_activity_validation_summary.txt").write_text(summary)

    out_json = P4 / "results/p4_activity_validation_report.json"
    out_json.write_text(json.dumps(report, indent=2))
    print(f"\nSaved: {out_json}")
    print(f"Wall time: {time.perf_counter() - t0:.1f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
