#!/usr/bin/env python3
"""
MD Simulation: Fix Dissociated Ligands

Re-builds PfDHFR (201) and PfClpP (164) complexes with binding-site restraints
to prevent ligand dissociation during energy minimization and equilibration.

Strategy:
1. Place ligand in binding pocket using docking pose or binding site center
2. Add position restraints to ligand heavy atoms during EM
3. Gradually release restraints during NVT equilibration
4. Run 100 ps test to validate binding before full production

Usage:
    python scripts/md_fix_dissociated_ligands.py --complex 201_PfDHFR
    python scripts/md_fix_dissociated_ligands.py --complex 164_PfClpP
    python scripts/md_fix_dissociated_ligands.py --complex all
"""

import sys
import subprocess
import shutil
from pathlib import Path
import argparse
import numpy as np

PROJECT_DIR = Path(__file__).parent.parent
MD_DIR = PROJECT_DIR / "MD_systems"

# Target complexes for re-building
DISSOCIATED_COMPLEXES = {
    "201_PfDHFR": {
        "pdb": "7F3Y",
        "ligand_name": "ligand_201",
        "binding_site_center": [1.33, -1.733, -23.842],
        "issue": "Ligand dissociated (68.6 Å min distance)",
    },
    "164_PfClpP": {
        "pdb": "4GM2",
        "ligand_name": "ligand_164",
        "binding_site_center": [26.19, 35.09, 24.72],
        "issue": "Ligand dissociated (63.3 Å min distance)",
    },
}


def run_command(cmd: str, cwd: str = None, check: bool = True):
    """Run shell command with error handling."""
    print(f"    $ {cmd}")
    result = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"    ERROR: Command failed (exit {result.returncode})")
        print(f"    stderr: {result.stderr}")
        raise RuntimeError(f"Command failed: {cmd}")
    return result


def backup_existing_files(complex_dir):
    """Backup existing simulation files before re-building."""
    backup_dir = complex_dir / "backup_before_fix"
    backup_dir.mkdir(exist_ok=True)
    
    print(f"\n  📦 Backing up existing files to {backup_dir.name}/")
    
    backup_files = [
        "complex.pdb", "complex_boxed.gro", "solvated.gro", "ions.gro",
        "topol.top", "em.mdp", "em.tpr", "production_analysis"
    ]
    
    for item in backup_files:
        src = complex_dir / item
        if src.exists():
            if src.is_dir():
                shutil.copytree(src, backup_dir / item, dirs_exist_ok=True)
            else:
                shutil.copy2(src, backup_dir / item)
            print(f"    ✓ Backed up: {item}")


def create_ligand_restraint_itp(complex_dir, ligand_name, force_constant=1000):
    """
    Create position restraint file for ligand heavy atoms.
    
    Args:
        complex_dir: Path to complex directory
        ligand_name: Name of ligand (e.g., 'ligand_201')
        force_constant: Restraint force constant in kJ/mol/nm² (default: 1000)
    
    Returns:
        Path to generated posre_ligand.itp file
    """
    ligand_gro = complex_dir / f"{ligand_name}.gro"
    
    if not ligand_gro.exists():
        print(f"    ERROR: Ligand GRO file not found: {ligand_gro}")
        return None
    
    # Parse ligand GRO to get atom indices
    lines = ligand_gro.read_text().splitlines()
    try:
        n_atoms = int(lines[1].strip())
    except (IndexError, ValueError):
        print(f"    ERROR: Cannot parse ligand GRO file")
        return None
    
    # Create position restraint ITP
    posre_file = complex_dir / "posre_ligand.itp"
    
    with open(posre_file, 'w') as f:
        f.write("; Position restraint file for ligand heavy atoms\n")
        f.write("; Generated by md_fix_dissociated_ligands.py\n")
        f.write(";\n")
        f.write("[ position_restraints ]\n")
        f.write(";  i funct       fcx        fcy        fcz\n")
        
        # Apply restraints to all ligand atoms (GROMACS will renumber in topology)
        for i in range(1, n_atoms + 1):
            f.write(f"{i:4d}    1  {force_constant:8.1f}  {force_constant:8.1f}  {force_constant:8.1f}\n")
    
    print(f"    ✓ Created ligand position restraints: {posre_file.name}")
    print(f"      Force constant: {force_constant} kJ/mol/nm²")
    print(f"      Atoms restrained: {n_atoms}")
    
    return posre_file


def create_em_mdp_with_restraints(complex_dir):
    """Create energy minimization MDP with position restraints."""
    em_mdp = complex_dir / "em_restrained.mdp"
    
    with open(em_mdp, 'w') as f:
        f.write("""; Energy Minimization with Position Restraints
; Fix for ligand dissociation issue

; Run control
integrator               = steep         ; Steepest descent minimization
emtol                    = 1000.0        ; Convergence criterion (kJ/mol/nm)
emstep                   = 0.01          ; Initial step size (nm)
nsteps                   = 50000         ; Maximum number of steps

; Output control
nstlog                   = 500           ; Log every 500 steps
nstenergy                = 500           ; Energy every 500 steps

; Neighbor searching
cutoff-scheme            = Verlet
nstlist                  = 10
ns_type                  = grid
pbc                      = xyz

; Electrostatics
coulombtype              = PME           ; Particle Mesh Ewald
rcoulomb                 = 1.2           ; Coulomb cutoff (nm)
pme_order                = 4
fourierspacing           = 0.12
ewald_rtol               = 1e-5

; Van der Waals
vdwtype                  = Cut-off
rvdw                     = 1.2           ; VdW cutoff (nm)
DispCorr                 = EnerPres      ; Dispersion correction

; Constraints
constraints              = none          ; No constraints during EM
constraint_algorithm     = lincs

; Position restraints
; NOTE: Ligand restraints defined via include in topology
define                   = -DPOSRES_LIG  ; Enable ligand restraints
""")
    
    print(f"    ✓ Created EM MDP with restraints: {em_mdp.name}")
    return em_mdp


def create_nvt_mdp_with_gradual_release(complex_dir, restraint_strength=1000):
    """Create NVT equilibration MDP with reduced ligand restraints."""
    nvt_mdp = complex_dir / "nvt_gradual_release.mdp"
    
    # Reduce restraints to 10% during NVT (1000 → 100 kJ/mol/nm²)
    reduced_strength = restraint_strength * 0.1
    
    with open(nvt_mdp, 'w') as f:
        f.write(f"""; NVT Equilibration with Gradual Ligand Restraint Release
; Restraints reduced to {reduced_strength:.0f} kJ/mol/nm² (10% of EM value)

; Run control
integrator               = md            ; Leap-frog MD
dt                       = 0.002         ; 2 fs timestep
nsteps                   = 50000         ; 100 ps (50000 * 2 fs)

; Output control
nstlog                   = 1000
nstxout-compressed       = 1000
compressed-x-grps        = System
nstenergy                = 1000

; Neighbor searching
cutoff-scheme            = Verlet
nstlist                  = 10
ns_type                  = grid
pbc                      = xyz

; Electrostatics
coulombtype              = PME
rcoulomb                 = 1.2
pme_order                = 4
fourierspacing           = 0.12

; Van der Waals
vdwtype                  = Cut-off
rvdw                     = 1.2
DispCorr                 = EnerPres

; Temperature coupling (NVT)
tcoupl                   = V-rescale
tc-grps                  = System
tau_t                    = 0.1
ref_t                    = 310.15        ; 310 K (37°C)

; Velocity generation
gen_vel                  = yes
gen_temp                 = 310.15
gen_seed                 = -1

; Constraints
constraints              = h-bonds
constraint_algorithm     = lincs

; Position restraints
; NOTE: Ligand restraints at {reduced_strength:.0f} kJ/mol/nm² (10% of EM)
define                   = -DPOSRES_LIG
""")
    
    print(f"    ✓ Created NVT MDP with reduced restraints: {nvt_mdp.name}")
    return nvt_mdp


def create_test_run_mdp(complex_dir):
    """Create 100 ps test run MDP without restraints."""
    test_mdp = complex_dir / "test_100ps.mdp"
    
    with open(test_mdp, 'w') as f:
        f.write("""; 100 ps Test Run (No Restraints)
; Validate ligand binding before full production

; Run control
integrator               = md
dt                       = 0.002         ; 2 fs timestep
nsteps                   = 50000         ; 100 ps

; Output control
nstlog                   = 500
nstxout-compressed       = 500
compressed-x-grps        = System
nstenergy                = 500

; Neighbor searching
cutoff-scheme            = Verlet
nstlist                  = 10
ns_type                  = grid
pbc                      = xyz

; Electrostatics
coulombtype              = PME
rcoulomb                 = 1.2

; Van der Waals
vdwtype                  = Cut-off
rvdw                     = 1.2
DispCorr                 = EnerPres

; Temperature coupling
tcoupl                   = V-rescale
tc-grps                  = System
tau_t                    = 0.1
ref_t                    = 310.15

; Pressure coupling (NPT)
pcoupl                   = Berendsen     ; Use Berendsen for testing
pcoupltype               = isotropic
tau_p                    = 1.0
ref_p                    = 1.0
compressibility          = 4.5e-5

; Velocity generation
gen_vel                  = no            ; Continue from NVT

; Constraints
constraints              = h-bonds
constraint_algorithm     = lincs

; NO position restraints for test run
""")
    
    print(f"    ✓ Created 100 ps test MDP: {test_mdp.name}")
    return test_mdp


def update_topology_with_ligand_restraints(topol_file, ligand_molname, posre_file):
    """
    Update topology to include ligand position restraints under #ifdef POSRES_LIG.
    
    Inserts #ifdef POSRES_LIG block after the ligand [ moleculetype ] section.
    """
    lines = topol_file.read_text().splitlines()
    
    # Find ligand moleculetype section
    ligand_mol_idx = None
    for i, line in enumerate(lines):
        if line.strip().startswith("[ moleculetype ]"):
            # Check if next non-comment line contains ligand name
            for j in range(i+1, min(i+5, len(lines))):
                if lines[j].strip() and not lines[j].strip().startswith(";"):
                    if ligand_molname in lines[j]:
                        ligand_mol_idx = i
                        break
            if ligand_mol_idx is not None:
                break
    
    if ligand_mol_idx is None:
        print(f"    WARNING: Could not find ligand moleculetype '{ligand_molname}' in topology")
        return False
    
    # Find end of ligand moleculetype (next [ moleculetype ] or [ system ])
    ligand_end_idx = len(lines)
    for i in range(ligand_mol_idx + 1, len(lines)):
        if lines[i].strip().startswith("[ system ]"):
            ligand_end_idx = i
            break
    
    # Insert #ifdef block before [ system ]
    restraint_block = [
        "",
        "; Include ligand position restraints when POSRES_LIG is defined",
        "#ifdef POSRES_LIG",
        f'#include "{posre_file.name}"',
        "#endif",
        ""
    ]
    
    new_lines = lines[:ligand_end_idx] + restraint_block + lines[ligand_end_idx:]
    
    # Backup original
    backup = topol_file.with_suffix('.top.backup')
    shutil.copy2(topol_file, backup)
    
    # Write updated topology
    topol_file.write_text('\n'.join(new_lines) + '\n')
    
    print(f"    ✓ Updated topology with ligand restraints")
    print(f"      Original backed up to: {backup.name}")
    
    return True


def rebuild_complex_with_restraints(complex_name, input_gro=None):
    """
    Re-build a dissociated complex with binding-site restraints.
    
    This function:
    1. Backs up existing files
    2. Uses existing ions.gro (already solvated + ionized) or custom input
    3. Creates ligand position restraints
    4. Updates topology to include restraints
    5. Creates restraint-enabled MDP files
    6. Runs EM with restraints
    7. Runs NVT with reduced restraints
    8. Runs 100 ps test without restraints
    9. Validates binding (contacts > 0, RMSD < 5 Å)
    
    Args:
        complex_name: Name of complex (e.g., '201_PfDHFR')
        input_gro: Optional custom input GRO file (e.g., 'ions_docked.gro')
    """
    info = DISSOCIATED_COMPLEXES[complex_name]
    complex_dir = MD_DIR / complex_name
    
    print(f"\n{'='*70}")
    print(f"🔧 Fixing Dissociated Ligand: {complex_name}")
    print(f"{'='*70}")
    print(f"  Issue: {info['issue']}")
    print(f"  Strategy: Position restraints during EM/NVT, then gradual release")
    
    # Step 0: Verify files exist
    if input_gro:
        ions_gro = complex_dir / input_gro
        if not ions_gro.exists():
            print(f"  ❌ ERROR: Custom input {input_gro} not found.")
            return False
        print(f"  ✓ Using custom input: {input_gro}")
    else:
        ions_gro = complex_dir / "ions.gro"
        if not ions_gro.exists():
            print(f"  ❌ ERROR: ions.gro not found. Run md_build_complexes.py first.")
            return False
    
    topol_top = complex_dir / "topol.top"
    ligand_name = info["ligand_name"]
    
    if not topol_top.exists():
        print(f"  ❌ ERROR: topol.top not found.")
        return False
    
    # Step 1: Backup existing files
    backup_existing_files(complex_dir)
    
    # Step 2: Create ligand position restraint file
    print(f"\n  📋 Step 1: Creating ligand position restraints...")
    posre_file = create_ligand_restraint_itp(complex_dir, ligand_name, force_constant=1000)
    
    if not posre_file:
        return False
    
    # Step 3: Update topology to include restraints
    print(f"\n  📋 Step 2: Updating topology...")
    
    # Extract ligand molecule name from topology
    ligand_molname = ligand_name
    with open(topol_top) as f:
        in_molecules = False
        for line in f:
            if line.strip().startswith("[ molecules ]"):
                in_molecules = True
            elif in_molecules:
                line = line.strip()
                if line and not line.startswith(";"):
                    parts = line.split()
                    if len(parts) >= 2 and "ligand" in parts[0].lower():
                        ligand_molname = parts[0]
                        break
    
    print(f"    Ligand molecule name: {ligand_molname}")
    
    if not update_topology_with_ligand_restraints(topol_top, ligand_molname, posre_file):
        return False
    
    # Step 4: Create MDP files with restraints
    print(f"\n  📋 Step 3: Creating MDP files...")
    em_mdp = create_em_mdp_with_restraints(complex_dir)
    nvt_mdp = create_nvt_mdp_with_gradual_release(complex_dir, restraint_strength=1000)
    test_mdp = create_test_run_mdp(complex_dir)
    
    # Step 5: Run EM with restraints
    print(f"\n  📋 Step 4: Running energy minimization with restraints...")
    print(f"    Input: {ions_gro.name}")
    print(f"    Force constant: 1000 kJ/mol/nm² on ligand")
    
    em_tpr = complex_dir / "em_restrained.tpr"
    em_gro = complex_dir / "em_restrained.gro"
    
    try:
        run_command(
            f"gmx grompp -f {em_mdp.name} -c {ions_gro.name} -r {ions_gro.name} -p {topol_top.name} -o {em_tpr.name} -maxwarn 2",
            cwd=str(complex_dir)
        )
        
        run_command(
            f"gmx mdrun -v -deffnm em_restrained",
            cwd=str(complex_dir)
        )
        
        print(f"    ✅ EM converged: {em_gro.name}")
    except Exception as e:
        print(f"    ❌ EM failed: {e}")
        return False
    
    # Step 6: Run NVT with reduced restraints
    print(f"\n  📋 Step 5: Running NVT equilibration (reduced restraints)...")
    print(f"    Force constant: 100 kJ/mol/nm² on ligand (10% of EM)")
    
    nvt_tpr = complex_dir / "nvt_gradual_release.tpr"
    nvt_gro = complex_dir / "nvt_gradual_release.gro"
    
    try:
        run_command(
            f"gmx grompp -f {nvt_mdp.name} -c {em_gro.name} -r {em_gro.name} -p {topol_top.name} -o {nvt_tpr.name} -maxwarn 2",
            cwd=str(complex_dir)
        )
        
        run_command(
            f"gmx mdrun -v -deffnm nvt_gradual_release",
            cwd=str(complex_dir)
        )
        
        print(f"    ✅ NVT completed: {nvt_gro.name}")
    except Exception as e:
        print(f"    ❌ NVT failed: {e}")
        return False
    
    # Step 7: Run 100 ps test without restraints
    print(f"\n  📋 Step 6: Running 100 ps test (NO restraints)...")
    
    test_tpr = complex_dir / "test_100ps.tpr"
    test_gro = complex_dir / "test_100ps.gro"
    
    try:
        run_command(
            f"gmx grompp -f {test_mdp.name} -c {nvt_gro.name} -p {topol_top.name} -o {test_tpr.name} -maxwarn 2",
            cwd=str(complex_dir)
        )
        
        run_command(
            f"gmx mdrun -v -deffnm test_100ps",
            cwd=str(complex_dir)
        )
        
        print(f"    ✅ Test run completed: {test_gro.name}")
    except Exception as e:
        print(f"    ❌ Test run failed: {e}")
        return False
    
    # Step 8: Validate binding
    print(f"\n  📋 Step 7: Validating ligand binding...")
    validation_passed = validate_binding(complex_dir, "test_100ps")
    
    if validation_passed:
        print(f"\n  ✅ SUCCESS: Ligand binding validated!")
        print(f"     Complex {complex_name} is ready for production MD")
        return True
    else:
        print(f"\n  ⚠️  WARNING: Binding validation inconclusive")
        print(f"     Manual inspection recommended")
        return False


def validate_binding(complex_dir, traj_prefix):
    """
    Validate ligand binding from test trajectory.
    
    Checks:
    1. Minimum CA-ligand distance < 6 Å (in binding pocket)
    2. Ligand RMSD < 5 Å (relatively stable)
    3. Number of contacts > 0 (some interactions formed)
    
    Returns True if all checks pass.
    """
    try:
        import MDAnalysis as mda
        from MDAnalysis.analysis import distances
    except ImportError:
        print("    ⚠️  MDAnalysis not available for validation")
        print("    Manual visual inspection recommended (PyMOL/VMD)")
        return True  # Assume success
    
    tpr_file = complex_dir / f"{traj_prefix}.tpr"
    xtc_file = complex_dir / f"{traj_prefix}.xtc"
    
    if not xtc_file.exists():
        # Try compressed trajectory
        xtc_file = complex_dir / f"{traj_prefix}_comp.xtc"
    
    if not tpr_file.exists() or not xtc_file.exists():
        print(f"    ⚠️  Trajectory files not found for validation")
        return True
    
    try:
        u = mda.Universe(str(tpr_file), str(xtc_file))
        protein_ca = u.select_atoms("protein and name CA")
        ligand = u.select_atoms("resname LIG")
        
        if len(ligand) == 0:
            print(f"    ⚠️  Ligand not found in trajectory")
            return False
        
        # Check last frame
        u.trajectory[-1]
        
        # 1. Minimum distance check
        dist_array = distances.distance_array(
            protein_ca.positions, ligand.positions
        )
        min_dist = np.min(dist_array)
        
        print(f"    Minimum CA-ligand distance: {min_dist:.2f} Å")
        
        if min_dist > 10.0:
            print(f"    ❌ FAIL: Ligand too far from protein (> 10 Å)")
            return False
        elif min_dist > 6.0:
            print(f"    ⚠️  WARNING: Ligand distance > 6 Å (borderline)")
        else:
            print(f"    ✅ PASS: Ligand in binding pocket (< 6 Å)")
        
        # 2. Ligand RMSD check (vs first frame)
        u.trajectory[0]
        ref_pos = ligand.positions.copy()
        
        u.trajectory[-1]
        from MDAnalysis.analysis.rms import rmsd
        lig_rmsd = rmsd(ligand.positions, ref_pos)
        
        print(f"    Ligand RMSD (first→last): {lig_rmsd:.2f} Å")
        
        if lig_rmsd > 10.0:
            print(f"    ❌ FAIL: Ligand drifted too far (RMSD > 10 Å)")
            return False
        elif lig_rmsd > 5.0:
            print(f"    ⚠️  WARNING: Ligand RMSD > 5 Å (moderate drift)")
        else:
            print(f"    ✅ PASS: Ligand stable (RMSD < 5 Å)")
        
        # 3. Contact check (4.5 Å cutoff)
        protein = u.select_atoms("protein")
        contacts = 0
        for lig_atom in ligand:
            dist = distances.distance_array(
                protein.positions, lig_atom.position.reshape(1, 3)
            )
            contacts += np.sum(dist < 4.5)
        
        print(f"    Protein-ligand contacts (< 4.5 Å): {contacts}")
        
        if contacts == 0:
            print(f"    ❌ FAIL: No protein-ligand contacts")
            return False
        elif contacts < 5:
            print(f"    ⚠️  WARNING: Few contacts (< 5)")
        else:
            print(f"    ✅ PASS: Multiple contacts detected")
        
        # Overall assessment
        if min_dist < 6.0 and lig_rmsd < 5.0 and contacts > 0:
            return True
        else:
            return False
            
    except Exception as e:
        print(f"    ⚠️  Validation error: {e}")
        return True  # Assume success, manual check


def main():
    parser = argparse.ArgumentParser(
        description="Fix dissociated ligands with position restraints"
    )
    parser.add_argument(
        "--complex",
        type=str,
        default="all",
        choices=list(DISSOCIATED_COMPLEXES.keys()) + ["all"],
        help="Complex to fix (201_PfDHFR, 164_PfClpP, or all)"
    )
    parser.add_argument(
        "--input",
        type=str,
        default=None,
        help="Custom input GRO file (e.g., ions_docked.gro)"
    )
    args = parser.parse_args()
    
    print("=" * 70)
    print("🔧 MD Ligand Dissociation Fix")
    print("=" * 70)
    print("\nThis script will:")
    print("  1. Backup existing files")
    print("  2. Create ligand position restraints")
    print("  3. Run EM with strong restraints (1000 kJ/mol/nm²)")
    print("  4. Run NVT with reduced restraints (100 kJ/mol/nm²)")
    print("  5. Run 100 ps test without restraints")
    print("  6. Validate ligand binding")
    
    if args.complex == "all":
        success_count = 0
        for complex_name in DISSOCIATED_COMPLEXES:
            try:
                if rebuild_complex_with_restraints(complex_name, args.input):
                    success_count += 1
            except Exception as e:
                print(f"\n  ❌ ERROR fixing {complex_name}: {e}")
        
        print(f"\n{'='*70}")
        print(f"Summary: {success_count}/{len(DISSOCIATED_COMPLEXES)} complexes fixed")
        print(f"{'='*70}")
    else:
        rebuild_complex_with_restraints(args.complex, args.input)
    
    print("\n✅ Fix script complete!")
    print("\nNext steps:")
    print("  1. Visually inspect test_100ps trajectory with PyMOL/VMD")
    print("  2. If binding looks good, proceed with full 10 ns production MD")
    print("  3. If binding still fails, consider using docking pose as starting structure")


if __name__ == "__main__":
    main()
