#!/usr/bin/env python3
"""Generate ligand ITP file for GROMACS from SMILES using OpenFF.

Usage:
    python p2_generate_ligand_itp.py SMILES output.itp
"""
import sys
from pathlib import Path

smiles = sys.argv[1]
output_itp = Path(sys.argv[2])

# OpenFF + AmberTools
from openff.toolkit import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.units import unit

# Create OpenFF molecule
mol = Molecule.from_smiles(smiles)
mol.generate_conformers(n_conformers=1)

# Load force field
ff = ForceField("openff-2.2.0.offxml")

# Parameterize
omm_system = ff.create_openmm_system(
    mol.to_topology(),
    charges=mol.compute_partial_charges_am1bcc()
)

# Extract forces for bonded terms
import openmm
from openmm import app

# Write ITP
with open(output_itp, "w") as f:
    f.write(f"; Ligand ITP generated from SMILES: {smiles}\n")
    f.write(f"; Generated by OpenFF 2.2.0 + SMIRNOFF\n")
    f.write(f"; Atom types: OpenFF (placeholder, will be converted)\n")
    f.write(f"\n")
    f.write(f"[ moleculetype ]\n")
    f.write(f"UNL     3\n")
    f.write(f"\n")
    f.write(f"[ atoms ]\n")

    # Get atoms
    omm_top = mol.to_topology().to_openmm()
    atoms = list(omm_top.atoms())

    for i, atom in enumerate(atoms):
        elem = atom.element.symbol
        # Map OpenFF atom types to CHARMM-like naming for GROMACS
        charge = atom.partial_charge.to(unit.elementary_charge).magnitude
        mass = atom.element.atomic_mass.to(unit.amu).magnitude
        f.write(f"  {i+1:5d}  {elem:>4s}  1  UNL  {elem:>4s}  {i+1:5d}  {charge:10.6f}  {mass:8.4f}\n")

    f.write(f"\n")
    f.write(f"[ bonds ]\n")

    # Get bonded terms
    for force in omm_system.getForces():
        if isinstance(force, openmm.HarmonicBondForce):
            for bond_idx in range(force.getNumBonds()):
                p1, p2, k, r0 = force.getBondParameters(bond_idx)
                f.write(f"  {p1+1:5d}  {p2+1:5d}  1  {r0.value_in_unit(unit.nanometer):10.6f}  {k.value_in_unit(unit.kilojoule_per_mole/unit.nanometer**2):10.4f}\n")

    f.write(f"\n")
    f.write(f"[ angles ]\n")

    for force in omm_system.getForces():
        if isinstance(force, openmm.HarmonicAngleForce):
            for angle_idx in range(force.getNumAngles()):
                p1, p2, p3, k, theta = force.getAngleParameters(angle_idx)
                f.write(f"  {p1+1:5d}  {p2+1:5d}  {p3+1:5d}  1  {theta.value_in_unit(unit.radian):10.6f}  {k.value_in_unit(unit.kilojoule_per_mole/unit.radian**2):10.4f}\n")

    f.write(f"\n")
    f.write(f"[ dihedrals ]\n")

    for force in omm_system.getForces():
        if isinstance(force, openmm.PeriodicTorsionForce):
            for torsion_idx in range(force.getNumTorsions()):
                p1, p2, p3, p4, periodicity, phase, k = force.getTorsionParameters(torsion_idx)
                f.write(f"  {p1+1:5d}  {p2+1:5d}  {p3+1:5d}  {p4+1:5d}  1  "
                        f"{periodicity}  {phase.value_in_unit(unit.radian):10.6f}  "
                        f"{k.value_in_unit(unit.kilojoule_per_mole):10.4f}\n")

    f.write(f"\n")
    f.write(f"[ exclusions ]\n")
    f.write(f"; 1-2, 1-3, and 1-4 exclusions handled by force field\n")

print(f"ITP written to {output_itp}")
print(f"Atoms: {mol.n_atoms}")
print(f"Bonds: {sum(1 for f in omm_system.getForces() if isinstance(f, openmm.HarmonicBondForce) for _ in range(f.getNumBonds()))}")
