#!/usr/bin/env python3
"""Exhaustive, read-only preflight for the four parent-study MD systems.

This script deliberately does not create inputs, copy coordinates, synthesize
force-field manifests, call GROMACS, or authorize a run. It resolves the
historical policy identifiers to the canonical on-disk directories and reports
all missing or invalid prerequisites so remediation can be done transparently.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from md_forcefield_manifest import validate as validate_forcefield_manifest

PROJECT_DIR = Path(__file__).resolve().parents[1]
SYSTEM_ROOT = PROJECT_DIR / "MD_systems"
OUTPUT_DEFAULT = PROJECT_DIR / "results" / "metrics" / "parent_md_preflight.json"

SYSTEMS = {
    "201_DHFR": "201_PfDHFR",
    "438_ATP4": "438_PfATP4",
    "164_ClpP": "164_PfClpP",
    "214_CRT": "214_PfCRT",
}
# These are required inputs for the guarded pipeline/policy. `em.gro`,
# `nvt.gro`, and `nvt.cpt` are generated by earlier stages and are therefore
# reported when present but are not incorrectly required before minimisation.
REQUIRED_FILES = ("ions.gro", "topol.top", "npt.gro", "npt.cpt")
OPTIONAL_STAGE_FILES = ("em.gro", "nvt.gro", "nvt.cpt")
REQUIRED_POLICY = {
    "cohort_id": "P2_PARENT_STUDY_MD_4",
    "temperature_k": 310.15,
    "protein_force_field": "CHARMM36m",
    "ligand_force_field": "CGenFF",
    "water_model": "TIP3P",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def inspect(alias: str, canonical: str) -> dict:
    system_dir = SYSTEM_ROOT / canonical
    required = {}
    optional_stage_outputs = {}
    blockers: list[str] = []
    if not system_dir.is_dir():
        blockers.append("missing canonical system directory")
    for filename in REQUIRED_FILES:
        path = system_dir / filename
        present = path.is_file() and path.stat().st_size > 0
        required[filename] = {
            "path": str(path),
            "present_nonempty": present,
            "size_bytes": path.stat().st_size if path.is_file() else 0,
            "sha256": sha256(path) if present else None,
        }
        if not present:
            blockers.append(f"missing/empty {filename}")
    for filename in OPTIONAL_STAGE_FILES:
        path = system_dir / filename
        present = path.is_file() and path.stat().st_size > 0
        optional_stage_outputs[filename] = {
            "path": str(path),
            "present_nonempty": present,
            "size_bytes": path.stat().st_size if path.is_file() else 0,
            "sha256": sha256(path) if present else None,
        }

    manifest_path = system_dir / "forcefield_manifest.json"
    manifest = None
    if not manifest_path.is_file():
        blockers.append("missing forcefield_manifest.json")
    else:
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            blockers.append(f"invalid forcefield_manifest.json: {exc}")
        if isinstance(manifest, dict):
            strict_errors = validate_forcefield_manifest(manifest, system_dir)
            blockers.extend(f"strict force-field validation: {error}" for error in strict_errors)
            for key, expected in {"system_name": canonical, **REQUIRED_POLICY}.items():
                if manifest.get(key) != expected:
                    blockers.append(
                        f"manifest {key}={manifest.get(key)!r}, expected {expected!r}"
                    )
            hash_map = {
                "ions.gro": "ions_sha256",
                "topol.top": "topology_sha256",
                "npt.gro": "coordinates_sha256",
                "npt.cpt": "checkpoint_sha256",
            }
            for filename, key in hash_map.items():
                actual = required[filename]["sha256"]
                if manifest.get(key) != actual:
                    blockers.append(f"manifest {key} does not match {filename}")

    return {
        "policy_alias": alias,
        "canonical_directory": canonical,
        "system_dir": str(system_dir),
        "required_files": required,
        "optional_stage_outputs": optional_stage_outputs,
        "forcefield_manifest": {
            "path": str(manifest_path),
            "present": manifest_path.is_file(),
            "sha256": sha256(manifest_path) if manifest_path.is_file() else None,
        },
        "blockers": blockers,
        "status": "READY" if not blockers else "BLOCKED",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_DEFAULT)
    args = parser.parse_args()

    systems = [inspect(alias, canonical) for alias, canonical in SYSTEMS.items()]
    blocked = [row for row in systems if row["status"] != "READY"]
    record = {
        "schema": "p2-parent-md-input-preflight/v2",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "read_only_inputs": True,
        "report_written": True,
        "execution_performed": False,
        "gromacs_launched": False,
        "execution_authorized": False,
        "cohort_id": "P2_PARENT_STUDY_MD_4",
        "policy": REQUIRED_POLICY,
        "system_count": len(systems),
        "ready_system_count": len(systems) - len(blocked),
        "blocked_system_count": len(blocked),
        "status": "READY_FOR_EXPLICIT_REVIEW" if not blocked else "FAIL_CLOSED_BLOCKED",
        "scope_note": "Four-system input/provenance gate; it does not validate completed trajectories or historical execution.",
        "hash_scope": ["ions.gro", "topol.top", "npt.gro", "npt.cpt", "forcefield_manifest.json"],
        "systems": systems,
        "remediation_rule": "Generate candidate-specific CHARMM36m+CGenFF/TIP3P inputs and independently verify all hashes; never copy historical GAFF2/ACPYPE coordinates or fabricate manifests.",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(record, indent=2, sort_keys=True))
    return 0 if not blocked else 2


if __name__ == "__main__":
    raise SystemExit(main())
